# Generated by Django 4.2.11 on 2026-03-03 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('execution', '0003_initial'),
        ('input_file', '0002_auto_20260302_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_key', models.CharField(help_text="Key from ETL config (e.g., 'facture_data')", max_length=100)),
                ('original_filename', models.CharField(help_text="User's original filename", max_length=500)),
                ('uploaded_file', models.FileField(upload_to='inputs/')),
                ('file_size', models.BigIntegerField(help_text='Size in bytes')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('INVALID', 'Invalid')], default='UPLOADED', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='execution.execution')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'input_files',
                'ordering': ['uploaded_at'],
                'unique_together': {('execution', 'file_key')},
            },
        ),
    ]
