# Generated by Django 4.2.11 on 2026-03-16 08:14

import apps.input_file.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_file', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputfile',
            name='uploaded_file',
            field=models.FileField(upload_to=apps.input_file.models.input_file_upload_path),
        ),
    ]
