# Generated by Django 4.2.11 on 2026-03-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_file', '0004_alter_inputfile_uploaded_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inputfile',
            unique_together=set(),
        ),
    ]
