# Generated by Django 4.2.11 on 2026-03-03 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etl', '0002_auto_20260302_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('zip_file', models.FileField(upload_to='etls/')),
                ('extracted_path', models.CharField(blank=True, max_length=500)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_etls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'etls',
                'ordering': ['-created_at'],
            },
        ),
    ]
