# Generated by Django 4.2.11 on 2026-03-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etl',
            name='config_file_path',
            field=models.CharField(blank=True, help_text="Relative path to the config file, e.g. 'config/config.json'", max_length=500),
        ),
        migrations.AddField(
            model_name='etl',
            name='entry_point_path',
            field=models.CharField(blank=True, help_text="Relative path inside ZIP to the entry script, e.g. 'src/main.py'", max_length=500),
        ),
        migrations.AddField(
            model_name='etl',
            name='python_version',
            field=models.CharField(blank=True, help_text="Python version to use, e.g. '3.11'", max_length=20),
        ),
        migrations.AddField(
            model_name='etl',
            name='requirements_path',
            field=models.CharField(blank=True, help_text='Relative path to requirements.txt', max_length=500),
        ),
    ]
