# Generated by Django 4.2.11 on 2026-03-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_etl_config_file_path_etl_entry_point_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etl',
            name='resolved_config_file',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='etl',
            name='resolved_entry_point',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='etl',
            name='resolved_requirements',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='etl',
            name='config_file_path',
            field=models.CharField(blank=True, help_text="Filename of the config file, e.g. 'config.json'. Searched recursively.", max_length=500),
        ),
        migrations.AlterField(
            model_name='etl',
            name='entry_point_path',
            field=models.CharField(blank=True, help_text="Filename of the entry script, e.g. 'main.py'. Searched recursively.", max_length=500),
        ),
        migrations.AlterField(
            model_name='etl',
            name='requirements_path',
            field=models.CharField(blank=True, help_text="Filename of requirements file, e.g. 'requirements.txt'. Searched recursively.", max_length=500),
        ),
    ]
