# Generated by Django 4.2.11 on 2026-03-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_etl_resolved_config_file_etl_resolved_entry_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etl',
            name='deps_installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etl',
            name='path_classifications',
            field=models.JSONField(blank=True, default=dict, help_text='Admin classifies which config keys point to input/output paths'),
        ),
        migrations.AddField(
            model_name='etl',
            name='shared_venv_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='etl',
            name='config_file_path',
            field=models.CharField(blank=True, help_text="Filename of the config file, e.g. 'config.json'", max_length=500),
        ),
        migrations.AlterField(
            model_name='etl',
            name='entry_point_path',
            field=models.CharField(blank=True, help_text="Filename of the entry script, e.g. 'main.py'", max_length=500),
        ),
        migrations.AlterField(
            model_name='etl',
            name='python_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='etl',
            name='requirements_path',
            field=models.CharField(blank=True, help_text="Filename of requirements file, e.g. 'requirements.txt'", max_length=500),
        ),
    ]
