# Generated by Django 4.2.11 on 2026-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usergroup'),
        ('etl', '0006_etl_deps_installed_at_etl_path_classifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etl',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to allow all users. Add groups to restrict access.', related_name='etls', to='accounts.usergroup'),
        ),
        migrations.AlterField(
            model_name='etl',
            name='config_file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='etl',
            name='entry_point_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='etl',
            name='path_classifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='etl',
            name='requirements_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
