# Generated by Django 6.0.5 on 2026-06-02 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_etl_allowed_groups_alter_etl_config_file_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etl',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Individual users allowed to see and run this ETL.', related_name='allowed_etls', to=settings.AUTH_USER_MODEL),
        ),
    ]
