# Generated by Django 4.2.11 on 2026-02-25 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique ETL name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='What does this ETL do?')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('zip_file', models.FileField(help_text='Uploaded ETL zip package', upload_to='etls/')),
                ('extracted_path', models.CharField(blank=True, help_text='Path where zip was extracted', max_length=500)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Parsed ETL configuration')),
                ('is_active', models.BooleanField(default=False, help_text='Is this ETL available to users?')),
                ('is_validated', models.BooleanField(default=False, help_text='Has this ETL passed validation?')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation errors if any')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_etls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ETL',
                'verbose_name_plural': 'ETLs',
                'db_table': 'etls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_label', models.CharField(blank=True, help_text="Optional label (e.g., 'January 2024')", max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATING', 'Validating Inputs'), ('VALIDATED', 'Inputs Validated'), ('VALIDATION_FAILED', 'Validation Failed'), ('INSTALLING_DEPS', 'Installing Dependencies'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('work_dir', models.CharField(help_text='Execution workspace directory', max_length=500)),
                ('archive_path', models.CharField(blank=True, help_text='Path to archived execution', max_length=500)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('return_code', models.IntegerField(blank=True, help_text='Exit code: 0=success, non-zero=failure', null=True)),
                ('stdout_log', models.TextField(blank=True, help_text='Standard output')),
                ('stderr_log', models.TextField(blank=True, help_text='Error output')),
                ('error_message', models.TextField(blank=True)),
                ('etl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.etl')),
                ('launched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launched_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execution',
                'verbose_name_plural': 'Executions',
                'db_table': 'executions',
                'ordering': ['-launched_at'],
            },
        ),
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(help_text='Absolute path to file', max_length=1000)),
                ('file_size', models.BigIntegerField(help_text='Size in bytes')),
                ('file_type', models.CharField(help_text='File type (excel, csv, pdf, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_files', to='core.execution')),
            ],
            options={
                'db_table': 'output_files',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ETL_UPLOADED', 'ETL Uploaded'), ('ETL_VALIDATED', 'ETL Validated'), ('ETL_ACTIVATED', 'ETL Activated'), ('ETL_DEACTIVATED', 'ETL Deactivated'), ('EXECUTION_CREATED', 'Execution Created'), ('INPUT_UPLOADED', 'Input File Uploaded'), ('EXECUTION_STARTED', 'Execution Started'), ('EXECUTION_COMPLETED', 'Execution Completed'), ('EXECUTION_FAILED', 'Execution Failed'), ('OUTPUT_DOWNLOADED', 'Output File Downloaded'), ('EXECUTION_ARCHIVED', 'Execution Archived')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('etl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.etl')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.execution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_key', models.CharField(help_text="Key from ETL config (e.g., 'facture_data')", max_length=100)),
                ('original_filename', models.CharField(help_text="User's original filename", max_length=500)),
                ('uploaded_file', models.FileField(upload_to='inputs/')),
                ('file_size', models.BigIntegerField(help_text='Size in bytes')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('INVALID', 'Invalid')], default='UPLOADED', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='core.execution')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'input_files',
                'ordering': ['uploaded_at'],
                'unique_together': {('execution', 'file_key')},
            },
        ),
    ]
