# Generated by Django 4.2.11 on 2026-03-03 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etl', '0003_initial'),
        ('execution', '0002_auto_20260302_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_label', models.CharField(blank=True, help_text="Optional label (e.g., 'January 2024')", max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATING', 'Validating Inputs'), ('VALIDATED', 'Inputs Validated'), ('VALIDATION_FAILED', 'Validation Failed'), ('INSTALLING_DEPS', 'Installing Dependencies'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('work_dir', models.CharField(help_text='Execution workspace directory', max_length=500)),
                ('archive_path', models.CharField(blank=True, help_text='Path to archived execution', max_length=500)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('return_code', models.IntegerField(blank=True, help_text='Exit code: 0=success, non-zero=failure', null=True)),
                ('stdout_log', models.TextField(blank=True, help_text='Standard output')),
                ('stderr_log', models.TextField(blank=True, help_text='Error output')),
                ('error_message', models.TextField(blank=True)),
                ('runtime_config', models.JSONField(blank=True, default=dict, help_text='Snapshot of the runtime configuration passed to the ETL process (paths to inputs, outputs directory, etc.).')),
                ('python_version_used', models.CharField(blank=True, help_text="Python version that actually ran this execution (e.g. '3.11.8').", max_length=20)),
                ('venv_path', models.CharField(blank=True, help_text='Filesystem path to the uv/virtual environment used for this run.', max_length=500)),
                ('dependencies_installed', models.BooleanField(default=False, help_text='True when requirements.txt was installed successfully in the venv.')),
                ('dependencies_log', models.TextField(blank=True, help_text='Raw log output from the dependency installation step (uv / pip).')),
                ('etl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='etl.etl')),
                ('launched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launched_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execution',
                'verbose_name_plural': 'Executions',
                'db_table': 'executions',
                'ordering': ['-launched_at'],
            },
        ),
    ]
