# Generated by Django 4.2.11 on 2026-03-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ['-launched_at']},
        ),
        migrations.AddField(
            model_name='execution',
            name='config_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Only the keys the user changed from the ETL default'),
        ),
        migrations.AddField(
            model_name='execution',
            name='execution_config',
            field=models.JSONField(blank=True, default=dict, help_text='Merged config for this run: ETL base config + user overrides'),
        ),
        migrations.AddField(
            model_name='execution',
            name='notify_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='execution',
            name='output_delivery',
            field=models.CharField(choices=[('app', 'App only'), ('email', 'Email only'), ('both', 'App and email')], default='app', max_length=10),
        ),
        migrations.AddField(
            model_name='execution',
            name='report_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='execution',
            name='report_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='archive_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='execution',
            name='dependencies_installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='execution',
            name='dependencies_log',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='execution_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='execution',
            name='python_version_used',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='execution',
            name='return_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='runtime_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='execution',
            name='stderr_log',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='stdout_log',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='venv_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='execution',
            name='work_dir',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
