# Generated by Django 4.2.11 on 2026-04-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_alter_execution_options_execution_config_overrides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='path_classifications',
            field=models.JSONField(blank=True, default=dict, help_text="User-chosen path classifications for this execution. Values: 'input', 'output', 'skip'. Merged over etl.path_classifications at check time."),
        ),
    ]
