# Generated by Django 4.2.11 on 2026-06-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_execution_path_classifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='execution',
            name='process_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
