# Generated by Django 4.2.11 on 2026-06-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_execution_cancel_requested_execution_process_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='hidden_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
