# Generated by Django 6.0.5 on 2026-07-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0008_execution_rerun_from_step_stepexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='step_input_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
