# Generated by Django 6.0.5 on 2026-07-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0009_step_input_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepexecution',
            name='raw_input_refs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
