# Generated by Django 4.2.11 on 2026-03-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('output_file', '0001_initial'),
    ]

    operations = [
    ]
