# Generated by Django 4.2.11 on 2026-03-03 21:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution', '0003_initial'),
        ('output_file', '0002_auto_20260302_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(help_text='Absolute path to file', max_length=1000)),
                ('file_size', models.BigIntegerField(help_text='Size in bytes')),
                ('file_type', models.CharField(help_text='e.g. excel, csv, pdf', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_files', to='execution.execution')),
            ],
            options={
                'verbose_name': 'Output File',
                'verbose_name_plural': 'Output Files',
                'db_table': 'output_files',
                'ordering': ['created_at'],
            },
        ),
    ]
