# Generated by Django 4.2.11 on 2026-03-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_initial'),
        ('output_file', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outputfile',
            unique_together={('execution', 'filename')},
        ),
    ]
