# Generated by Django 4.2.11 on 2026-04-24 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0007_etl_allowed_groups_alter_etl_config_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('time_of_day', models.TimeField(help_text='Local server time to trigger (HH:MM)')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('notify_email', models.EmailField(blank=True, help_text="Email to notify when a scheduled run is due. Defaults to the ETL creator's email.", max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('etl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='etl.etl')),
            ],
            options={
                'db_table': 'etl_schedules',
            },
        ),
    ]
