# Generated by Django 6.0.5 on 2026-05-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etlschedule',
            name='notify_email',
        ),
        migrations.AddField(
            model_name='etlschedule',
            name='backup_email',
            field=models.EmailField(blank=True, help_text='An extra address that always receives a CC of the notification.', max_length=254),
        ),
        migrations.AddField(
            model_name='etlschedule',
            name='month_of_year',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='etlschedule',
            name='notify_specific_email',
            field=models.EmailField(blank=True, help_text='Admin-only: a specific email to notify (overrides creator).', max_length=254),
        ),
        migrations.AddField(
            model_name='etlschedule',
            name='notify_target',
            field=models.CharField(choices=[('creator', 'ETL creator only'), ('group', 'Entire group'), ('specific', 'Specific email')], default='creator', help_text='Admin-only: who should receive the launch notification.', max_length=10),
        ),
        migrations.AlterField(
            model_name='etlschedule',
            name='day_of_month',
            field=models.IntegerField(blank=True, help_text="1–28. Use 28 to mean 'end of month' (safe for February).", null=True),
        ),
        migrations.AlterField(
            model_name='etlschedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='etlschedule',
            name='time_of_day',
            field=models.TimeField(help_text='Server local time to trigger (HH:MM)'),
        ),
    ]
