# Generated by Django 4.2.11 on 2026-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etlschedule',
            name='notify_email',
        ),
        migrations.AddField(
            model_name='etlschedule',
            name='backup_email',
            field=models.EmailField(blank=True, help_text='An extra address that always receives a CC of the notification.', max_length=254),
        ),
        migrations.AddField(
            model_name='etlschedule',
            name='notify_specific_email',
            field=models.EmailField(blank=True, help_text='Admin-only: a specific email to notify (overrides creator).', max_length=254),
        ),
        migrations.AddField(
            model_name='etlschedule',
            name='notify_target',
            field=models.CharField(choices=[('creator', 'ETL creator only'), ('group', 'Entire group'), ('specific', 'Specific email')], default='creator', help_text='Admin-only: who should receive the launch notification.', max_length=10),
        ),
        migrations.AlterField(
            model_name='etlschedule',
            name='time_of_day',
            field=models.TimeField(help_text='Server local time to trigger (HH:MM)'),
        ),
    ]
