# Generated by Django 6.0.5 on 2026-06-04 12:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_etl_allowed_users'),
        ('scheduling', '0002_remove_etlschedule_notify_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='etlschedule',
            name='day_of_month',
            field=models.IntegerField(blank=True, help_text='1–31. Days beyond month length clamp to the last day (e.g. 31 → 30 in April).', null=True),
        ),
        migrations.CreateModel(
            name='ScheduleRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=10)),
                ('time_of_day', models.TimeField(help_text='Preferred run time (HH:MM)')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('month_of_year', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('note', models.TextField(blank=True, help_text='Why do you need this schedule?')),
                ('approved_scope', models.CharField(blank=True, choices=[('requester', 'Just me'), ('group', 'My group'), ('specific', 'Specific email')], help_text='Who gets notified when the schedule fires.', max_length=10)),
                ('approved_specific_email', models.EmailField(blank=True, max_length=254)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_requests', to='etl.etl')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_schedule_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'etl_schedule_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
