# Generated by Django 4.2.11 on 2026-05-08 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etl', '0007_etl_allowed_groups_alter_etl_config_file_path_and_more'),
        ('scheduling', '0002_remove_etlschedule_notify_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etlschedule',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='etlschedule',
            name='day_of_year',
            field=models.IntegerField(blank=True, help_text='Day of month for yearly schedule (1-28)', null=True),
        ),
        migrations.AddField(
            model_name='etlschedule',
            name='launched_for',
            field=models.ForeignKey(blank=True, help_text='User who should see and launch the pending execution. NULL means the ETL creator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_scheduled_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etlschedule',
            name='month_of_year',
            field=models.IntegerField(blank=True, help_text='1=Jan … 12=Dec (yearly only)', null=True),
        ),
        migrations.AlterField(
            model_name='etlschedule',
            name='backup_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='etlschedule',
            name='etl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='etl.etl'),
        ),
        migrations.AlterField(
            model_name='etlschedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='etlschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='etlschedule',
            name='notify_specific_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='etlschedule',
            name='notify_target',
            field=models.CharField(choices=[('creator', 'ETL creator only'), ('group', 'Entire group'), ('specific', 'Specific email')], default='creator', max_length=20),
        ),
        migrations.AlterField(
            model_name='etlschedule',
            name='time_of_day',
            field=models.TimeField(help_text='Local server time to fire'),
        ),
        migrations.AlterModelTable(
            name='etlschedule',
            table=None,
        ),
    ]
